### ISSUE TITLE
go build: error when building sdjournal

### ISSUE THREAD

**Issue by AymC** [M00NLIG7/ChopChopGo#10]
Really neat tool, thank you!
I got this error when trying to build with `go build` (Ubuntu 20.04.5 LTS): 
```
# github.com/coreos/go-systemd/v22/sdjournal
../../go/pkg/mod/github.com/coreos/go-systemd/v22@v22.5.0/sdjournal/journal.go:27:11: fatal error: systemd/sd-journal.h: No such file or directory
27 | // #include <systemd/sd-journal.h>
   |           ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
In case it helps others, I was able to fix this by installing an additional systemd package : `apt-get install libsystemd-dev`
